/* File:        $Id: License.txt,v $
 * Revision:    $Revision: 1.4 $
 * Author:      $Author: csr $
 * Date:        $Date: 2005/04/11 16:29:16 $
 *
 * Copyright Det Kongelige Bibliotek og Statsbiblioteket, Danmark
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

package dk.netarkivet.common.exceptions;

import java.sql.SQLException;

import junit.framework.TestCase;

import dk.netarkivet.testutils.StringAsserts;

/**
 * csr forgot to comment this!
 *
 * @author csr
 * @since Jan 15, 2009
 */

public class ExceptionUtilsTester extends TestCase {

    /**
     * this test confirms that the message generated by getSQLExceptionCause() contains
     * all the information in the original SQLException
     */
    public void testGetSQLExceptionCause() {
        SQLException ex1 = new SQLException("reason1", "state1", 101);
        SQLException ex2 = new SQLException("reason2", "state2", 102);
        SQLException ex3 = new SQLException("reason3", "state3", 103);
        ex1.setNextException(ex2);
        ex2.setNextException(ex3);
        String message = ExceptionUtils.getSQLExceptionCause(ex1);
        System.out.println(message);
        StringAsserts.assertStringContains("Compound exception should contain "
                                           + "references to all three "
                   + "reasons, states, and codes", message, "reason1",
                     "reason2", "reason3", "state1", "state2", "state3",
                     "101", "102", "103");
    }


}
