filedesc://NETARKIVET-20041208103817-00000-pc801.sb.statsbiblioteket.dk.arc 0.0.0.0 20041208103817 text/plain 1243
1 1 InternetArchive
URL IP-address Archive-date Content-type Archive-length
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<arcmetadata xmlns="http://archive.org/arc/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:arc="http://archive.org/arc/1.0/" xsi:schemaLocation="http://archive.org/arc/1.0/ http://www.archive.org/arc/1.0/arc.xsd">
<arc:software>Heritrix 1.2.0 http://crawler.archive.org</arc:software>
<arc:hostname>pc801.sb.statsbiblioteket.dk</arc:hostname>
<arc:ip>130.225.24.247</arc:ip>
<dcterms:isPartOf>netarkivet</dcterms:isPartOf>
<dc:description>Profile: Simple crawl</dc:description>
<arc:operator>Admin</arc:operator>
<dc:date xsi:type="dcterms:W3CDTF">2004-12-08T10:38:15+00:00</dc:date>
<arc:http-header-user-agent>Mozilla/5.0 (compatible; heritrix/1.2.0 +http://www.netarkivet.dk/website/info.html)</arc:http-header-user-agent>
<arc:http-header-from>bja@statsbiblioteket.dk</arc:http-header-from>
<arc:robots>classic</arc:robots>
<dc:format>ARC file version 1.1</dc:format>
<dcterms:conformsTo xsi:type="dcterms:URI">http://www.archive.org/web/researcher/ArcFileFormat.php</dcterms:conformsTo>
</arcmetadata>


dns:www.netarkivet.dk 130.226.231.141 20041208103817 text/dns 61
20041208103817
www.netarkivet.dk.	10563	IN	A	130.226.231.141

http://www.netarkivet.dk/robots.txt 130.226.231.141 20041208103817 text/html 472
HTTP/1.1 404 Not Found
Date: Wed, 08 Dec 2004 10:38:17 GMT
Server: Apache/1.3.27 (Unix) PHP/4.3.8 mod_jk/1.2.5 mod_perl/1.27
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>404 Not Found</TITLE>
</HEAD><BODY>
<H1>Not Found</H1>
The requested URL /robots.txt was not found on this server.<P>
<HR>
<ADDRESS>Apache/1.3.27 Server at www.netarkivet.dk Port 80</ADDRESS>
</BODY></HTML>

http://www.netarkivet.dk/ 130.226.231.141 20041208103817 text/html 13442
HTTP/1.1 200 OK
Date: Wed, 08 Dec 2004 10:38:17 GMT
Server: Apache/1.3.27 (Unix) PHP/4.3.8 mod_jk/1.2.5 mod_perl/1.27
Connection: close
Content-Type: text/html

<html>

<head>
<meta http-equiv="content-type" content="text/html;charset=iso-8859-1">
<meta name="generator" content="Microsoft FrontPage 4.0">
<title>Netarkivet - fase 2</title>
<link rel="stylesheet" href="/website/includes/netarkivet.css">
<csactionitem name="B7D34BA35"></csactionitem>
<csactions>
			<csaction name="B7D34BA35" class="Netscape CSS Fix" type="onload"></csaction>
		</csactions>
<csscriptdict>
<script language=javascript><!--
CSInit = new Array;
function CSScriptInit() {
if(typeof(skipPage) != "undefined") { if(skipPage) return; }
idxArray = new Array;
for(var i=0;i<CSInit.length;i++)
	idxArray[i] = i;
CSAction2(CSInit, idxArray);}
CSStopExecution = false;
function CSAction(array) { 
	return CSAction2(CSAct, array);
}
function CSAction2(fct, array) { 
	var result;
	for (var i=0;i<array.length;i++) {
		if(CSStopExecution) return false; 
		var actArray = fct[array[i]];
		if (actArray == null) return false;
		var tempArray = new Array;
		for(var j=1;j<actArray.length;j++) {
			if((actArray[j] != null) && (typeof(actArray[j]) == "object") && (actArray[j].length == 2)) {
				if(actArray[j][0] == "VAR") {
					tempArray[j] = CSStateArray[actArray[j][1]];
				}
				else {
					if(actArray[j][0] == "ACT") {
						tempArray[j] = CSAction(new Array(new String(actArray[j][1])));
					}
				else
					tempArray[j] = actArray[j];
				}
			}
			else
				tempArray[j] = actArray[j];
		}			
		result = actArray[0](tempArray);
	}
	return result;
}
CSAct = new Object;

function CSFixFct() {
	var d = document; var w = window;
	if (d.cs.csFix.w != w.innerWidth || d.cs.csFix.h != w.innerHeight) {
		d.location = d.location; }
}
function CSNSFix(action) { 
	var d = document; var w = window;
	if ((navigator.appName == 'Netscape') && (parseInt(navigator.appVersion) == 4)) {
		if (typeof d.cs == 'undefined') { 
			d.cs = new Object;
			d.cs.csFix = new Object; 
		} else if (CSIsFrame (w) == true) CSFixFct();
		d.cs.csFix.w = w.innerWidth;
		d.cs.csFix.h = w.innerHeight; 
		window.onresize = CSFixFct;
	  }
}
function CSIsFrame (window) {
	var rootWindow = window.parent;
	if (rootWindow == 'undefined') return false;
	for (i = 0; i < rootWindow.frames.length; i++)
		if (window == rootWindow.frames[i]) return true;
	return false;
}

// --></script>
</csactiondict>
		<csactiondict>
			<script><!--
CSInit[CSInit.length] = new Array(CSNSFix);

// --></script>
		</csactiondict>
	</head>

<!-- ------------  BODY starter HER ------------------ -->

<body bgcolor="white" text="black" link="#8b0000" alink="#8b0000" vlink="gray" onload="CSScriptInit();">

<!-- TOP SEKTION -->

<center>
<table border="0" cellpadding="0" cellspacing="2">
<tr>
<td><font color="gray">
							<table cool width="827" height="900" border="0" cellpadding="0" cellspacing="0" gridx="16" showgridx usegridx gridy="16" showgridy usegridy>
								<tr height="126">

									<td width="826" height="126" colspan="12" valign="top" align="left" xpos="0"><img src="/website/grafik/ib-netarkivet_top_logoer.gif" width="780" border="0" height="126" usemap="#netarkivet_top_logoerb7e0b07c"></td>

<map name="netarkivet_top_logoerb7e0b07c">
<area shape="rect" coords="675,92,770,123" href="http://www.kb.dk/" target="_blank">
<area shape="rect" coords="563,92,663,123" href="http://www.statsbiblioteket.dk/" target="_blank">
</map>

<td width="1" height="126"><spacer type="block" width="1" height="126"></td>
								</tr>
								<tr height="26">
									<td width="14" height="26" colspan="2"></td>
									<td content csheight="19" width="128" height="26" colspan="3" valign="top" align="left" xpos="14">
										<div align="left">
											<h5><a href="index-en.htm">English</a></h5>
											<!-- <font face="Verdana,Arial,Helvetica,Geneva" size="1" color="gray">12/06/2001</font> --></div>
									</td>
									<td width="684" height="26" colspan="7"></td>
									<td width="1" height="26"><spacer type="block" width="1" height="26"></td>
								</tr>
								<tr height="8">
									<td width="165" height="8" colspan="8"></td>
									<td content csheight="620" width="488" height="747" rowspan="4" valign="top" align="left" xpos="165">
										<h1>Om netarkivet.dk - fase 2</h1>

										<h3>

<b>Netarkivet.dk er projektet, der planlægger at bevare Danmarks digitale kulturarv på Internettet,  så den kan gives videre til kommende generationer.</b>
<BR><BR>
I løbet af 2002 afsluttedes et pilotprojekt i et samarbejde mellem Det Kongelige Bibliotek, Statsbiblioteket og Center for Internetforskning som havde til formål at udvikle en grundlæggende strategi for arkivering af dansk internet-materiale.
<BR><BR>
En af pilotprojektets centrale anbefalinger var at høste materialerne efter tre forskellige principper: automatisk "tværsnithøstning", "selektiv" høstning, hvor særligt vigtige netsteder følges tæt, samt "begivenhedshøstning", hvor man høster internet-dækningen af særlige begivenheder (som f.eks. et folketingsvalg, en eu-afstemning eller et kongeligt bryllup).
<BR><BR>
I forlængelse af pilotprojektet påbegyndte Det Kongelige Bibliotek og Statsbiblioteket i sommeren 2003 arbejdet i anden fase af projektet, hvis formål er at videreudvikle strategien fra pilotprojektet samt undersøge behovet for eventuelle ændringer i pligtafleveringsloven.
<BR><BR>
En del af dette arbejde munder ud i en rapport til Kulturministeriet i april 2004. Rapporten skal gennem analyse-, udviklings- og testarbejde give konkrete anvisninger på hvordan en permanent løsning på området kan gennemføres.
<BR><BR>
I dette samarbejde har Det Kongelige Bibliotek særligt fokus på tværsnitshøstningen, mens Statsbiblioteket koncentrerer sig om selektiv høstning, hændelses-baseret høstning og evt. afleveret materiale. De to biblioteker arbejder tæt sammen om hele arkivets etablering og udvikler i fællesskab både strategier for og software til materialernes indsamling, arkivering, bevaring og tilgængeliggørelse.
<BR><BR>


</h3>

									</td>
									<td width="26" height="8" colspan="2"></td>
									<td content csheight="561" width="147" height="747" rowspan="4" valign="top" align="left" xpos="679">
										<h2><font color="#8b0000">Nyt</font></h2>
										
              <div align="left"> 


                <!--
											<span class="nyheder">Den afsluttende rapport for pilotprojektet 'netarkivet.dk' er nu f&aelig;rdig<br>
												<a href="/rap/index-da.htm">L&aelig;s mere</a></span><BR><BR>
											<span class="nyheder">Fransk lovforslag om pligtaflevering af alt netmateriale<br>
												<a href="/papers/Notat_om_LSI.pdf">L&aelig;s dansk notat</a></span><BR><BR>
-->

<span class="nyheder">
4. november 2004:<BR>
To nye love er forelagt folketinget,
<a href="http://www.ft.dk/Samling/20041/lovforslag/L78/index.htm">lov om &aelig;ndring af ophavsretsloven</a> og
<a href="http://www.ft.dk/Samling/20041/lovforslag/L77/index.htm">lov om pligtaflevering</a>.  F&oslash;rstebehandlingen fandt sted 12. november 2004.
</span>

<BR><BR>

<span class="nyheder">
26.07.2004:<BR>
Projektrapporten: <b>"Archive format and metadate requirements"</b> er offentliggjort.<br>
<a href="website/publications/index-da.htm">L&aelig;s mere her</a>
 </span>

<BR><BR>

<span class="nyheder">
6.7.2004: Pressemeddelelse:<BR>
<strong><a href="website/press/Bryllup-20040706.pdf">Kronprinseparret for&aelig;res en ekstra bryllupsrejse i en web-tidsmaskine</a></strong>
 </span>

<BR><BR>

<span class="nyheder">
Netarkivet.dk har offentliggjort <strong>Java Arc Proxy Viewer</strong> den 7.7.2004<br>
<a href="website/sources/index-da.htm#proxyviewer">Hent den her</a>
</span>

<BR><BR>

<span class="nyheder">
Projektrapporten: <b>"Concerning Etags and Datestamps"</b> er offentliggjort.<br>
<a href="website/publications/index-da.htm">L&aelig;s mere her</a>
</span>

<BR><BR>

<span class="nyheder">
Projektrapporten: <b>"Handling file formats"</b> er offentliggjort.<br>
<a href="website/publications/index-da.htm">L&aelig;s mere her</a>
</span>
        
<BR><BR>

<span class="nyheder">
Netarkivet.dk har offentliggjort en ny version (0.2) af <strong>Java Arc v&aelig;rkt&oslash;jer</strong><br>
<a href="website/sources/index-da.htm">Hent dem her</a>
</span>

<BR><BR>

<span class="nyheder">
Artiklen <strong>Web Archive Activities in Denmark</strong> i RLG DigiNews fra 15. juni 2004 er tilg&aelig;ngelig 
<a href="http://www.rlg.org/en/page.php?Page_ID=17661#article0" target="_blank">her</a> (p&aring; engelsk)
</span>

<BR><BR>
                


              </div>
</td>
									<td width="1" height="8"><spacer type="block" width="1" height="8"></td>
								</tr>
								<tr height="444">
									<td width="16" height="444" colspan="3"></td>
									<td width="128" height="444" colspan="3" valign="top" align="left" xpos="16">
									<!-- tekstfil til indsættelse i index.fil -->
<table border="0" cellpadding="6" cellspacing="2" width="128" bgcolor="#8b0000" height="405" background="/website/grafik/menu_background.gif">                                                                                       
 <tr>                                                                                             
   <td>
     <h4><BR><a href="/index-da.htm"><font color="white">Forside</font></a></h4>
      <h4><a href="/website/projdelt/index-da.htm"><font color="white">Projektdeltagere</font></a></h4>
      <h4><a href="/website/links/index-da.htm"><font color="white">Links</font></a></h4>
      <h4><a href="/website/publications/index-da.htm"><font color="white">Publikationer</font></a></h4>
      <h4><a href="/website/sources/index-da.htm"><font color="white">Kildetekster</font></a></h4>
      <h4><a href="/website/press/index-da.htm"><font color="white">Pressemeddelelser</font></a></h4>
      <h4><a href="/pilot-index-da.htm"><font color="white">Pilotprojektet</font></a></h4>
      <p><font face="Verdana,Arial,Helvetica,Geneva" size="1" color="white">
      <img height="140" width="111" src="/global/images/clear.gif">
      <br>Sidst opdateret<br>25. november 2004</font>
      </p>
      <br><br><br><br><br>
   </td>
 </tr>
</table>

									</td>
									<td width="7" height="444"></td>
									<td width="14" height="444" valign="top" align="left" xpos="151"><img src="/global/images/red_gradient.gif" width="4" height="400" border="0"></td>
									<td width="12" height="444"></td>
									<td width="14" height="444" valign="top" align="left" xpos="665"><img src="/global/images/red_gradient.gif" width="4" height="400" border="0"></td>
									<td width="1" height="444"><spacer type="block" width="1" height="444"></td>
								</tr>
								<tr height="29">
									<td width="13" height="295" rowspan="2"></td>
									<td content csheight="28" width="96" height="29" colspan="3" valign="top" align="left" xpos="13"><!-- <h5><a href="(Empty Reference!)">English</a></h5> --></td>
									<td width="56" height="29" colspan="4"></td>
									<td width="26" height="295" colspan="2" rowspan="2"></td>
									<td width="1" height="29"><spacer type="block" width="1" height="29"></td>
								</tr>
								<tr height="266">
									<td content csheight="80" width="131" height="266" colspan="5" valign="top" align="left" xpos="13">
										<div align="left">
											<!-- <h5><font color="gray">Projektet st&oslash;ttes &oslash;konomisk af </font><a href="http://www.deflink.dk/"><font color="gray">Danmarks Elektroniske Forskningsbibliotek</font></a></h5>--></div>
									</td>
									<td width="21" height="266" colspan="2"></td>
									<td width="1" height="266"><spacer type="block" width="1" height="266"></td>
								</tr>
								<tr height="1" cntrlrow>
									<td width="13" height="1"><spacer type="block" width="13" height="1"></td>
									<td width="1" height="1"><spacer type="block" width="1" height="1"></td>
									<td width="2" height="1"><spacer type="block" width="2" height="1"></td>
									<td width="93" height="1"><spacer type="block" width="93" height="1"></td>
									<td width="33" height="1"><spacer type="block" width="33" height="1"></td>
									<td width="2" height="1"><spacer type="block" width="2" height="1"></td>
									<td width="7" height="1"><spacer type="block" width="7" height="1"></td>
									<td width="14" height="1"><spacer type="block" width="14" height="1"></td>
									<td width="488" height="1"><spacer type="block" width="488" height="1"></td>
									<td width="12" height="1"><spacer type="block" width="12" height="1"></td>
									<td width="14" height="1"><spacer type="block" width="14" height="1"></td>
									<td width="147" height="1"><spacer type="block" width="147" height="1"></td>
									<td width="1" height="1"></td>
								</tr>
								<csnopos>
									<cspos xpos="0" ypos="0">



									</cspos>
									<cspos xpos="0" ypos="152">
										<!----------- Midterspalte til BRØDTEKSTEN ---------- -->
									</cspos>
									<cspos xpos="0" ypos="152">
										<!-- --------------- NYHEDS-SPALTE (TIL HØJRE) ------------------- -->
									</cspos>
								</csnopos>
							</table>
						</font></td>
</tr>
</table>


</center>
</body>
</html>



<!-- Ret ikke i denne fil.  Linien herover sørger for, at brugeren får
en index-XX.htm, der matcher det land, han er i. -->

http://www.netarkivet.dk/website/includes/netarkivet.css 130.226.231.141 20041208103818 text/css 1030
HTTP/1.1 200 OK
Date: Wed, 08 Dec 2004 10:38:18 GMT
Server: Apache/1.3.27 (Unix) PHP/4.3.8 mod_jk/1.2.5 mod_perl/1.27
Last-Modified: Tue, 20 Jan 2004 13:15:00 GMT
ETag: "2d4368-2ea-400d29d4"
Accept-Ranges: bytes
Content-Length: 746
Connection: close
Content-Type: text/css

h1   { color: #8b0000; font-weight: bold; font-size: 24px; font-family: Verdana, Arial, Helvetica, Geneva }h2 { color: black; font-weight: bold; font-size: 14px; font-family: Verdana, Arial, Helvetica, Geneva }h3  { color: black; font-weight: normal; font-size: 13px; font-family: Verdana, Arial, Helvetica, Geneva }h4   { color: white; font-weight: bold; font-size: 12px; font-family: Verdana, Arial, Helvetica, Geneva }h5 { color: white; font-weight: bold; font-size: 10px; font-family: Verdana, Arial, Helvetica, Geneva }h6 { color: white; font-weight: bold; font-size: 9px; font-family: Verdana, Arial, Helvetica, Geneva }.nyheder  { color: black; font-weight: normal; font-size: 11px; font-family: Verdana, Arial, Helvetica, Geneva }